"""Initial schema

Revision ID: c7f8c6adec0e
Revises: 
Create Date: 2026-09-06 22:30:25.380207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f8c6adec0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('horizon_start', sa.DateTime(), nullable=True),
    sa.Column('horizon_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('station_from', sa.String(), nullable=True),
    sa.Column('station_to', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['station_from'], ['stations.code'], ),
    sa.ForeignKeyConstraint(['station_to'], ['stations.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('location_km', sa.Float(), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('criticality_class', sa.String(), nullable=True),
    sa.Column('safety_flag', sa.Boolean(), nullable=True),
    sa.Column('condition_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_windows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('max_duration_min', sa.Integer(), nullable=True),
    sa.Column('power_block_allowed', sa.Boolean(), nullable=True),
    sa.Column('track_block_allowed', sa.Boolean(), nullable=True),
    sa.Column('signal_block_allowed', sa.Boolean(), nullable=True),
    sa.Column('availability_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('train_id', sa.String(), nullable=True),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('service_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_entry', sa.DateTime(), nullable=True),
    sa.Column('scheduled_exit', sa.DateTime(), nullable=True),
    sa.Column('train_type', sa.String(), nullable=True),
    sa.Column('priority_class', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('defect_type', sa.String(), nullable=False),
    sa.Column('defect_severity', sa.String(), nullable=False),
    sa.Column('reported_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('priority_class', sa.String(), nullable=True),
    sa.Column('required_duration_min', sa.Integer(), nullable=True),
    sa.Column('days_since_last_maintenance', sa.Integer(), nullable=True),
    sa.Column('overdue_days', sa.Integer(), nullable=True),
    sa.Column('safety_critical', sa.Boolean(), nullable=True),
    sa.Column('dependency_group', sa.String(), nullable=True),
    sa.Column('crew_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('block_id', sa.String(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('expected_impact', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block_windows.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_table('defects')
    op.drop_table('train_movements')
    op.drop_table('block_windows')
    op.drop_table('assets')
    op.drop_table('sections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stations')
    op.drop_table('plans')
    op.drop_table('departments')
    # ### end Alembic commands ###
