"""Add ML and Optimization tracking tables

Revision ID: f79fd530b144
Revises: c7f8c6adec0e
Create Date: 2026-09-06 22:33:34.578238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79fd530b144'
down_revision: Union[str, Sequence[str], None] = 'c7f8c6adec0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_registry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=True),
    sa.Column('solver_version', sa.String(), nullable=True),
    sa.Column('objective_profile', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_blocks_used', sa.Integer(), nullable=True),
    sa.Column('critical_tasks_completed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('prediction_timestamp', sa.DateTime(), nullable=True),
    sa.Column('risk_probability', sa.Float(), nullable=True),
    sa.Column('confidence_tier', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('feature_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('optimization_runs')
    op.drop_table('dataset_registry')
    op.drop_table('data_quality_events')
    # ### end Alembic commands ###
