from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.db.models import Asset, MaintenanceTask, BlockWindow, Station, Section, OptimizationRun, Prediction
import pandas as pd
import os
import json

router = APIRouter()

@router.get("/stations")
def get_stations(db: Session = Depends(get_db)):
    return db.query(Station).all()

@router.get("/sections")
def get_sections(db: Session = Depends(get_db)):
    return db.query(Section).all()

@router.get("/assets")
def get_assets(db: Session = Depends(get_db)):
    return db.query(Asset).all()

@router.get("/maintenance/tasks")
def get_tasks(db: Session = Depends(get_db)):
    return db.query(MaintenanceTask).all()

@router.get("/blocks/availability")
def get_blocks(db: Session = Depends(get_db)):
    return db.query(BlockWindow).all()

@router.get("/plans/optimized")
def get_optimized_plan(db: Session = Depends(get_db)):
    # Serve the ML optimizer CSV output from data/processed
    PROC_DIR = "data/processed"
    if os.path.exists(f"../{PROC_DIR}/optimized_plan.csv"):
        df = pd.read_csv(f"../{PROC_DIR}/optimized_plan.csv")
    elif os.path.exists(f"{PROC_DIR}/optimized_plan.csv"):
        df = pd.read_csv(f"{PROC_DIR}/optimized_plan.csv")
    else:
        return []
    return df.to_dict(orient="records")

@router.get("/models/health")
def get_model_health():
    # Load Model Card generated by train_models.py
    mc_path = "ml/models/model_card.json"
    if not os.path.exists(mc_path):
        mc_path = "../ml/models/model_card.json"
    if os.path.exists(mc_path):
        with open(mc_path, "r") as f:
            return json.load(f)
    return {"status": "unavailable"}

@router.get("/optimization/runs")
def get_opt_runs(db: Session = Depends(get_db)):
    return db.query(OptimizationRun).order_by(OptimizationRun.run_timestamp.desc()).limit(5).all()

